#!/usr/bin/env bash
# Scaffold the field-note-sharers attribution section on this wiki.
# Creates docs/<section>/index.md from the bundled template and prints sidebar wiring instructions.
#
# Canonical recipe lives at: supersuit-repos/curated-wiki-integrations/integrations/field-note-sharers/
# Templates here are intentionally duplicated so the wiki-template is self-contained at bootstrap time.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATE_DIR="$ROOT/scripts/templates/field-note-sharers"
DOCS="$ROOT/docs"

echo ""
echo "=== Field-note-sharers integration ==="
echo ""
echo "This section is the canonical attribution-layer pattern: one Markdown file per source"
echo "(named individual or firm) credited on this wiki. Optional dated field-note log per source."
echo ""

# Section folder slug
echo "Pick the section folder name. Common choices:"
echo "  1) mentors            (named individuals + private archetypes; principal audience)"
echo "  2) people-to-follow   (practitioners worth tracking; implementer audience)"
echo "  3) sources            (generic; mix of individuals and firms)"
echo "  4) field-note-sharers (literal noun; when the wiki is about attribution itself)"
echo "  5) custom             (enter your own)"
echo ""
read -r -p "Choice [1-5, default 1]: " CHOICE
CHOICE="${CHOICE:-1}"

case "$CHOICE" in
  1) SECTION_SLUG="mentors";            SECTION_TITLE="Mentors" ;;
  2) SECTION_SLUG="people-to-follow";   SECTION_TITLE="People to Follow" ;;
  3) SECTION_SLUG="sources";            SECTION_TITLE="Sources" ;;
  4) SECTION_SLUG="field-note-sharers"; SECTION_TITLE="Field-Note-Sharers" ;;
  5)
    read -r -p "Section folder slug (kebab-case, e.g. cited-thinkers): " SECTION_SLUG
    read -r -p "Human-readable section label (e.g. Cited Thinkers): " SECTION_TITLE
    ;;
  *)
    echo "Invalid choice; defaulting to 'mentors'."
    SECTION_SLUG="mentors"; SECTION_TITLE="Mentors"
    ;;
esac

# Allow the title to be overridden even for the default choices
read -r -p "Section label [$SECTION_TITLE]: " SECTION_TITLE_INPUT
SECTION_TITLE="${SECTION_TITLE_INPUT:-$SECTION_TITLE}"

# Section description for frontmatter
echo ""
echo "Section description (one sentence, under 200 chars, used for SEO + cards)."
echo "Default: 'Who the wisdom on this wiki comes from. Curated, attributed, not exhaustive.'"
read -r -p "Description: " SECTION_DESCRIPTION
SECTION_DESCRIPTION="${SECTION_DESCRIPTION:-Who the wisdom on this wiki comes from. Curated, attributed, not exhaustive.}"

# Intro paragraph (what the section is for, in this wiki's voice)
INTRO_PARAGRAPH="The substance on this wiki traces back to specific sources. This section names them, documents where each one sits relative to the rest of the wiki, and (optionally) keeps a chronological log of what was lifted from which piece of their work."

# Refuse to overwrite an existing section
SECTION_DIR="$DOCS/$SECTION_SLUG"
if [[ -d "$SECTION_DIR" ]]; then
  echo ""
  echo "ERROR: docs/$SECTION_SLUG/ already exists. Refusing to overwrite."
  echo "If you want to reset it, delete the folder first and re-run this script."
  exit 1
fi

mkdir -p "$SECTION_DIR"

# Render the section index from the template (simple sed substitution)
INDEX_OUT="$SECTION_DIR/index.md"
sed \
  -e "s|{{SECTION_TITLE}}|$SECTION_TITLE|g" \
  -e "s|{{SECTION_SLUG}}|$SECTION_SLUG|g" \
  -e "s|{{SECTION_DESCRIPTION}}|$SECTION_DESCRIPTION|g" \
  -e "s|{{INTRO_PARAGRAPH}}|$INTRO_PARAGRAPH|g" \
  "$TEMPLATE_DIR/section-index.md.template" > "$INDEX_OUT"

echo ""
echo "Wrote $INDEX_OUT"

# Print the sidebar snippet for manual paste
cat << EOF

=== Sidebar wiring (manual paste) ===

Add the following category to sidebars.ts, inside the 'primary' array.
A natural spot is right before the 'changelog' entry at the bottom:

    {
      type: 'category',
      label: '$SECTION_TITLE',
      collapsed: true,
      link: { type: 'doc', id: '$SECTION_SLUG/index' },
      items: [
        { type: 'autogenerated', dirName: '$SECTION_SLUG' },
      ],
    },

Why manual: sidebars.ts is hand-edited TypeScript. Programmatic insertion
is brittle and risks reformatting unrelated lines. The paste is one-time.

=== Adding sources ===

For each source you cite on this wiki, copy the source-page template:

  cp scripts/templates/field-note-sharers/source-page.md.template \\
     docs/$SECTION_SLUG/<source-slug>.md

Then replace the {{PLACEHOLDER}} fields in that file. The dated
'## Field Notes' section is optional — delete it if this wiki doesn't
maintain per-source field-note logs.

Don't forget to add each new source to the 'The sources' list inside
docs/$SECTION_SLUG/index.md as the section grows.

EOF
